import { wrapEffect } from './index.js';

export function cardPhoneEffect(ctx) {
  const imageUrl = ctx.config.imageUrl || '';
  return wrapEffect('card_phone', `
var IMAGE_URL=${JSON.stringify(imageUrl)};if(!IMAGE_URL){try{if(typeof completion==='function')completion('No card image configured')}catch(_){};return;}
var card=null,shown=false,dragging=false,removing=false,raf=0,baseX=0,baseY=0,cardW=0,cardH=0,dragStartX=0,dragStartY=0,dragBaseX=0,dragBaseY=0,neutralBeta=null,neutralGamma=null,targetGX=0,targetGY=0,currentGX=0,currentGY=0,targetRX=0,targetRY=0,currentRX=0,currentRY=0,gyroBound=false,permissionAsked=false,lastTap=0,tapX=0,tapY=0;
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function orientation(e){if(!shown||dragging||removing||typeof e.beta!=='number'||typeof e.gamma!=='number')return;if(neutralBeta===null||neutralGamma===null){neutralBeta=e.beta;neutralGamma=e.gamma;return;}var beta=clamp(e.beta-neutralBeta,-12,12),gamma=clamp(e.gamma-neutralGamma,-12,12);targetGX=gamma/12*120;targetGY=beta/12*95;targetRX=-beta/12*15;targetRY=gamma/12*18;}
function bindGyro(){if(gyroBound)return;gyroBound=true;window.addEventListener('deviceorientation',orientation,true);}
function requestGyro(){if(permissionAsked){bindGyro();return;}permissionAsked=true;try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){DeviceOrientationEvent.requestPermission().then(function(s){if(s==='granted')bindGyro()}).catch(function(){});}else bindGyro();}catch(_){bindGyro();}}
function loop(){currentGX+=(targetGX-currentGX)*.48;currentGY+=(targetGY-currentGY)*.48;currentRX+=(targetRX-currentRX)*.48;currentRY+=(targetRY-currentRY)*.48;if(card&&shown&&!removing){var gx=dragging?0:currentGX,gy=dragging?0:currentGY,rx=dragging?0:currentRX,ry=dragging?0:currentRY;card.style.transform='translate3d('+(baseX+gx)+'px,'+(baseY+gy)+'px,0) rotateX('+rx+'deg) rotateY('+ry+'deg)';}raf=requestAnimationFrame(loop);}
function removeCard(){if(card){try{card.remove()}catch(_){}}card=null;shown=false;dragging=false;removing=false;neutralBeta=neutralGamma=null;targetGX=targetGY=currentGX=currentGY=targetRX=targetRY=currentRX=currentRY=0;}
function flyAway(x,y){if(!card||removing)return;removing=true;card.style.transition='transform 260ms ease-in,opacity 240ms ease-in';card.style.transform='translate3d('+x+'px,'+y+'px,0) rotate(18deg) scale(.88)';card.style.opacity='0';setTimeout(removeCard,300);}
function checkOutside(){if(!card)return;var w=innerWidth,h=innerHeight;if(baseX+cardW*.45<0)return flyAway(-cardW-150,baseY);if(baseX+cardW*.55>w)return flyAway(w+150,baseY);if(baseY+cardH*.45<0)return flyAway(baseX,-cardH-150);if(baseY+cardH*.55>h)flyAway(baseX,h+150);}
function ds(e){if(!shown||removing||!e.touches||!e.touches[0])return;var t=e.touches[0];dragging=true;dragStartX=t.clientX;dragStartY=t.clientY;dragBaseX=baseX;dragBaseY=baseY;e.preventDefault();}
function dm(e){if(!dragging||!card||!e.touches||!e.touches[0])return;var t=e.touches[0];baseX=dragBaseX+t.clientX-dragStartX;baseY=dragBaseY+t.clientY-dragStartY;checkOutside();e.preventDefault();}
function de(e){dragging=false;checkOutside();try{e.preventDefault()}catch(_){}}
function show(){if(card){shown=true;neutralBeta=neutralGamma=null;card.style.pointerEvents='auto';card.style.transition='opacity 180ms ease';card.style.opacity='1';setTimeout(function(){if(card)card.style.transition='none'},220);return;}card=document.createElement('img');card.src=IMAGE_URL;card.draggable=false;Object.assign(card.style,{position:'fixed',left:'0',top:'0',width:Math.max(120,Math.min(230,innerWidth*.42))+'px',height:'auto',zIndex:'2147483647',pointerEvents:'auto',touchAction:'none',opacity:'0',filter:'drop-shadow(0 18px 22px rgba(0,0,0,.28))',transformOrigin:'50% 50%'});document.documentElement.appendChild(card);card.onload=function(){var r=card.getBoundingClientRect();cardW=r.width;cardH=r.height;baseX=(innerWidth-cardW)/2;baseY=(innerHeight-cardH)/2;shown=true;card.style.transform='translate3d('+baseX+'px,'+baseY+'px,0) scale(.68) rotate(-8deg)';void card.offsetWidth;card.style.transition='opacity 180ms ease,transform 240ms cubic-bezier(.2,.9,.25,1.12)';card.style.opacity='1';card.style.transform='translate3d('+baseX+'px,'+baseY+'px,0) scale(1)';setTimeout(function(){if(card)card.style.transition='none'},280);};card.addEventListener('touchstart',ds,{passive:false});card.addEventListener('touchmove',dm,{passive:false});card.addEventListener('touchend',de,{passive:false});card.addEventListener('touchcancel',de,{passive:false});}
function hide(){if(!card||!shown)return;shown=false;card.style.pointerEvents='none';card.style.transition='opacity 160ms ease,transform 180ms ease';card.style.opacity='0';card.style.transform='translate3d('+baseX+'px,'+baseY+'px,0) scale(.72) rotate(7deg)';}
function toggle(){if(shown)hide();else{requestGyro();show();}}
function ts(e){if(!e.touches||e.touches.length!==1)return;tapX=e.touches[0].clientX;tapY=e.touches[0].clientY;}
function te(e){if(!e.changedTouches||e.changedTouches.length!==1)return;var t=e.changedTouches[0];if(Math.hypot(t.clientX-tapX,t.clientY-tapY)>18){lastTap=0;return;}var now=Date.now();if(lastTap&&now-lastTap>60&&now-lastTap<380){lastTap=0;toggle();}else lastTap=now;}
document.addEventListener('touchstart',ts,{capture:true,passive:true});document.addEventListener('touchend',te,{capture:true,passive:true});loop();window.__cdsActiveEffect={destroy:function(){document.removeEventListener('touchstart',ts,true);document.removeEventListener('touchend',te,true);if(gyroBound)window.removeEventListener('deviceorientation',orientation,true);if(raf)cancelAnimationFrame(raf);removeCard();}};`);
}
