import { wrapEffect } from './index.js';

export function googleSingleEffect(ctx) {
  const imageUrl = ctx.config.imageUrl || '';
  return wrapEffect('google_single', `
var MAGIC_IMAGE=${JSON.stringify(imageUrl)};if(!MAGIC_IMAGE){try{if(typeof completion==='function')completion('No Google image configured')}catch(_){};return;}
var armed=false,autoRunning=false,destroyed=false,startAt=0,lastTap=0,tapX=0,tapY=0,scrollRAF=0,scanBusy=false,rescan=false,scanTimer=0,heartbeat=0,observer=null,records=[],byKey=new Map();
function vh(){return window.visualViewport?window.visualViewport.height:innerHeight;}function vw(){return window.visualViewport?window.visualViewport.width:innerWidth;}
function mainRoot(){return document.querySelector('#islrg')||document.querySelector('#search')||document.querySelector('#rso')||document.querySelector('main');}
function dialogRoots(){return Array.from(document.querySelectorAll("[role='dialog'],[aria-modal='true']")).filter(function(el){var r=el.getBoundingClientRect();return r.width>2&&r.height>2&&r.bottom>0&&r.top<vh();});}
function identity(img){return String(img.currentSrc||img.src||img.getAttribute('src')||'')+'|'+(img.naturalWidth||0)+'x'+(img.naturalHeight||0);}
function excluded(img){var alt=String(img.alt||'').toLowerCase(),src=String(img.currentSrc||img.src||'').toLowerCase();if(alt==='google'||alt.indexOf('google logo')>=0||src.indexOf('googlelogo')>=0)return true;try{return !!img.closest("header,nav,[role='banner'],form")}catch(_){return false}}
function tile(img,root){var node=img.parentElement,steps=0;while(node&&node!==root&&steps<9){if(node.tagName==='A'||node.getAttribute('role')==='button')return node;node=node.parentElement;steps++;}return img.parentElement||img;}
function inspect(img,root,kind){if(!img||img.tagName!=='IMG'||img.classList.contains('__cdsGoogleReplacement')||excluded(img))return null;var r;try{r=img.getBoundingClientRect()}catch(_){return null}if(r.width<68||r.height<52||r.bottom<=1||r.top>=vh()-1||r.right<=1||r.left>=vw()-1)return null;var key=tile(img,root);if(!key)return null;return{img:img,key:key,kind:kind,area:r.width*r.height,rect:r,identity:identity(img)};}
function drop(rec,again){try{rec.layer.remove()}catch(_){}byKey.delete(rec.key);var idx=records.indexOf(rec);if(idx>=0)records.splice(idx,1);if(again){try{rec.key.removeAttribute('data-cds-google')}catch(_){}}}
function targets(){var dialogs=dialogRoots(),roots=dialogs.length?dialogs:[mainRoot()],kind=dialogs.length?'dialog':'main',out=[];roots.filter(Boolean).forEach(function(root){var imgs=root.getElementsByTagName('img'),per=new Map();for(var i=0;i<imgs.length;i++){var info=inspect(imgs[i],root,kind);if(!info)continue;var prev=per.get(info.key);if(!prev||info.area>prev.area)per.set(info.key,info);}per.forEach(function(info){var ex=byKey.get(info.key);if(ex&&ex.img===info.img&&ex.identity===identity(info.img)&&ex.layer&&ex.layer.isConnected)return;if(ex)drop(ex,true);out.push(info);});});out.sort(function(a,b){return Math.abs(a.rect.top-b.rect.top)<14?a.rect.left-b.rect.left:a.rect.top-b.rect.top});return out;}
function hostFor(img){return img.offsetParent&&img.offsetParent.nodeType===1?img.offsetParent:document.body;}
function sync(rec){if(!rec.img.isConnected||!rec.layer.isConnected||!rec.host.isConnected)return false;var ir=rec.img.getBoundingClientRect(),hr=rec.host.getBoundingClientRect();if(ir.width<2||ir.height<2){rec.layer.style.display='none';return true;}rec.layer.style.display='block';rec.layer.style.left=(ir.left-hr.left+rec.host.scrollLeft)+'px';rec.layer.style.top=(ir.top-hr.top+rec.host.scrollTop)+'px';rec.layer.style.width=ir.width+'px';rec.layer.style.height=ir.height+'px';try{rec.layer.style.borderRadius=getComputedStyle(rec.img).borderRadius}catch(_){}return true;}
function replace(info){if(!armed||destroyed||!info.img.isConnected)return;var old=byKey.get(info.key);if(old&&old.img===info.img&&old.identity===identity(info.img))return;if(old)drop(old,true);try{info.key.setAttribute('data-cds-google','1')}catch(_){}var host=hostFor(info.img),layer=document.createElement('div'),image=document.createElement('img');image.className='__cdsGoogleReplacement';image.src=MAGIC_IMAGE;Object.assign(layer.style,{position:'absolute',overflow:'hidden',pointerEvents:'none',zIndex:'999',opacity:'0',transform:'scale(.96)',filter:'brightness(1.4) blur(2px)',transition:'opacity 280ms ease,transform 330ms cubic-bezier(.2,.8,.25,1),filter 330ms ease'});Object.assign(image.style,{position:'absolute',inset:'0',width:'100%',height:'100%',objectFit:'cover',objectPosition:'center'});layer.appendChild(image);host.appendChild(layer);var rec={img:info.img,key:info.key,host:host,layer:layer,kind:info.kind,identity:identity(info.img)};records.push(rec);byKey.set(info.key,rec);if(!sync(rec)){drop(rec,true);return;}void layer.offsetWidth;layer.style.opacity='1';layer.style.transform='scale(1)';layer.style.filter='none';}
function maintain(){var preview=dialogRoots().length>0;records.slice().forEach(function(rec){if(!rec.img.isConnected||!rec.key.isConnected||!rec.layer.isConnected||identity(rec.img)!==rec.identity){drop(rec,true);return;}if(rec.kind==='main'&&preview){rec.layer.style.display='none';return;}sync(rec);});}
function scan(done){if(!armed||destroyed)return;if(scanBusy){rescan=true;return;}scanBusy=true;var list=targets(),index=0;function finish(){scanBusy=false;if(rescan){rescan=false;schedule(25)}if(done)setTimeout(done,220);}function next(){if(!armed){scanBusy=false;return;}if(index>=list.length){finish();return;}replace(list[index++]);setTimeout(next,65);}next();}
function schedule(delay){if(!armed)return;clearTimeout(scanTimer);scanTimer=setTimeout(function(){scanTimer=0;scan();},delay||0);}
function scrollStep(done){if(dialogRoots().length){setTimeout(done,320);return;}var start=pageYOffset||0,max=Math.max(0,document.documentElement.scrollHeight-vh()),target=Math.min(max,start+vh()*.68),begin=performance.now();function frame(now){if(!autoRunning)return;var p=Math.min(1,(now-begin)/620),ease=p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2;scrollTo(0,start+(target-start)*ease);if(p<1)scrollRAF=requestAnimationFrame(frame);else{scrollRAF=0;setTimeout(done,340);}}scrollRAF=requestAnimationFrame(frame);}
function cycle(){if(!autoRunning)return;if(Date.now()-startAt>=10500){stopAuto();return;}scan(function(){if(!autoRunning)return;scrollStep(cycle);});}
function start(){armed=true;autoRunning=true;startAt=Date.now();cycle();setTimeout(function(){if(autoRunning)stopAuto()},10700);}
function stopAuto(){autoRunning=false;if(scrollRAF)cancelAnimationFrame(scrollRAF);scrollRAF=0;schedule(20);}
function disarm(){armed=false;autoRunning=false;if(scrollRAF)cancelAnimationFrame(scrollRAF);}
function onScroll(){if(armed)schedule(70);}
function ts(e){if(!e.touches||e.touches.length!==1)return;tapX=e.touches[0].clientX;tapY=e.touches[0].clientY;}
function te(e){if(!e.changedTouches||e.changedTouches.length!==1)return;var t=e.changedTouches[0];if(Math.hypot(t.clientX-tapX,t.clientY-tapY)>20){lastTap=0;return;}var now=Date.now();if(lastTap&&now-lastTap>60&&now-lastTap<390){lastTap=0;if(autoRunning)stopAuto();else if(armed)disarm();else start();}else lastTap=now;}
document.addEventListener('scroll',onScroll,true);document.addEventListener('touchstart',ts,{capture:true,passive:true});document.addEventListener('touchend',te,{capture:true,passive:true});observer=new MutationObserver(function(){if(armed){maintain();schedule(40);}});observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['src','srcset','role','aria-modal','aria-hidden']});heartbeat=setInterval(function(){if(armed&&!autoRunning){maintain();schedule(0);}},550);
window.__cdsActiveEffect={destroy:function(){destroyed=true;armed=false;autoRunning=false;clearInterval(heartbeat);clearTimeout(scanTimer);if(scrollRAF)cancelAnimationFrame(scrollRAF);if(observer)observer.disconnect();document.removeEventListener('scroll',onScroll,true);document.removeEventListener('touchstart',ts,true);document.removeEventListener('touchend',te,true);records.slice().forEach(function(r){drop(r,true);});}};`);
}
