import { wrapEffect } from './index.js';

export function productLettersEffect(ctx) {
  const name = String(ctx.config.name || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  const urls = Array.isArray(ctx.config.letterUrls) ? ctx.config.letterUrls : [];
  return wrapEffect('product_letters', `
var NAME=${JSON.stringify(name)},LETTER_IMAGES=${JSON.stringify(urls)};if(!NAME||!LETTER_IMAGES.length){try{if(typeof completion==='function')completion('Product-letter configuration incomplete')}catch(_){};return;}
var lastTap=0,tapX=0,tapY=0,overlays=[];
function visible(el){var r=el.getBoundingClientRect();return r.width>2&&r.height>2&&r.bottom>0&&r.top<innerHeight;}
function findCarousel(){var els=Array.from(document.querySelectorAll('div,section')),best=null,bestScore=-1;els.forEach(function(el){if(!visible(el)||el.scrollWidth<=el.clientWidth*1.15)return;var imgs=Array.from(el.getElementsByTagName('img')).filter(function(im){var r=im.getBoundingClientRect();return r.width>55&&r.height>45;});if(imgs.length<Math.min(3,NAME.length))return;var text=String(el.innerText||'').toLowerCase(),s=text.indexOf('sponsored')>=0,shop=text.indexOf('shop')>=0||text.indexOf('product')>=0,price=/[₹$€£]/.test(text);if(!s&&!shop&&!price)return;var score=imgs.length+(s?25:0)+(shop?10:0)+(price?10:0);if(score>bestScore){bestScore=score;best=el;}});return best;}
function tiles(container){var map=new Map();Array.from(container.getElementsByTagName('img')).forEach(function(im){var r=im.getBoundingClientRect();if(r.width<55||r.height<45)return;var key=im.closest("a,[role='button']")||im.parentElement;if(!key)return;var area=r.width*r.height,prev=map.get(key);if(!prev||area>prev.area)map.set(key,{img:im,key:key,area:area});});return Array.from(map.values()).slice(0,LETTER_IMAGES.length);}
function add(item,url,index){if(!url)return;var src=item.img,host=(src.offsetParent&&src.offsetParent.nodeType===1)?src.offsetParent:src.parentElement;if(!host)return;var r=src.getBoundingClientRect(),hr=host.getBoundingClientRect(),layer=document.createElement('div'),im=document.createElement('img');Object.assign(layer.style,{position:'absolute',left:(r.left-hr.left+host.scrollLeft)+'px',top:(r.top-hr.top+host.scrollTop)+'px',width:r.width+'px',height:r.height+'px',overflow:'hidden',pointerEvents:'none',zIndex:'999',opacity:'0',transform:'scale(.91)',filter:'brightness(1.5) blur(2px)',transition:'opacity 260ms ease,transform 320ms cubic-bezier(.2,.8,.25,1),filter 320ms ease'});try{layer.style.borderRadius=getComputedStyle(src).borderRadius}catch(_){}im.src=url;Object.assign(im.style,{position:'absolute',inset:'0',width:'100%',height:'100%',objectFit:'cover',objectPosition:'center'});layer.appendChild(im);host.appendChild(layer);overlays.push(layer);setTimeout(function(){layer.style.opacity='1';layer.style.transform='scale(1)';layer.style.filter='none';},index*95);}
function run(){overlays.forEach(function(x){try{x.remove()}catch(_){}});overlays=[];var c=findCarousel();if(!c)return;var items=tiles(c);for(var i=0;i<items.length&&i<LETTER_IMAGES.length;i++)add(items[i],LETTER_IMAGES[i],i);}
function ts(e){if(!e.touches||e.touches.length!==1)return;tapX=e.touches[0].clientX;tapY=e.touches[0].clientY;}
function te(e){if(!e.changedTouches||e.changedTouches.length!==1)return;var t=e.changedTouches[0];if(Math.hypot(t.clientX-tapX,t.clientY-tapY)>20){lastTap=0;return;}var now=Date.now();if(lastTap&&now-lastTap>60&&now-lastTap<390){lastTap=0;run();}else lastTap=now;}
document.addEventListener('touchstart',ts,{capture:true,passive:true});document.addEventListener('touchend',te,{capture:true,passive:true});window.__cdsActiveEffect={destroy:function(){document.removeEventListener('touchstart',ts,true);document.removeEventListener('touchend',te,true);overlays.forEach(function(x){try{x.remove()}catch(_){}});overlays=[];}};`);
}
